import React from 'react'
import './about.css'
import Logo from '../../assets/Mobile/Logo.svg'

const About = () => {
    return (
        <section className='filmbox__about-main'>
            <div className='filmbox__about-container'>
                <img className='filmbox__about-logo' src={Logo} alt='Logo' />
                <p className='filmbox__about-info'>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Dolor sit amet consectetur adipiscing elit. Eget velit aliquet sagittis id consectetur purus ut. Congue nisi vitae suscipit tellus. Quis viverra nibh cras pulvinar mattis nunc sed blandit libero. Arcu cursus vitae congue mauris rhoncus aenean vel. In est ante in nibh mauris cursus mattis molestie a. Tristique risus nec feugiat in fermentum posuere. Urna condimentum mattis pellentesque id nibh tortor id aliquet lectus. Velit egestas dui id ornare arcu odio ut sem nulla. At in tellus integer feugiat scelerisque varius morbi. Adipiscing elit pellentesque habitant morbi tristique senectus et netus et. Faucibus a pellentesque sit amet porttitor eget dolor. Sollicitudin nibh sit amet commodo nulla facilisi nullam. Id eu nisl nunc mi ipsum faucibus vitae. Amet consectetur adipiscing elit duis tristique sollicitudin. Id nibh tortor id aliquet lectus proin nibh. Mauris ultrices eros in cursus turpis massa tincidunt dui. Aliquet porttitor lacus luctus accumsan tortor posuere ac. Tempus urna et pharetra pharetra massa massa ultricies.
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Dolor sit amet consectetur adipiscing elit. Eget velit aliquet sagittis id consectetur purus ut. Congue nisi vitae suscipit tellus. Quis viverra nibh cras pulvinar mattis nunc sed blandit libero. Arcu cursus vitae congue mauris rhoncus aenean vel. In est ante in nibh mauris cursus mattis molestie a. Tristique risus nec feugiat in fermentum posuere. Urna condimentum mattis pellentesque id nibh tortor id aliquet lectus. Velit egestas dui id ornare arcu odio ut sem nulla. At in tellus integer feugiat scelerisque varius morbi. Adipiscing elit pellentesque habitant morbi tristique senectus et netus et. Faucibus a pellentesque sit amet porttitor eget dolor. Sollicitudin nibh sit amet commodo nulla facilisi nullam. Id eu nisl nunc mi ipsum faucibus vitae. Amet consectetur adipiscing elit duis tristique sollicitudin. Id nibh tortor id aliquet lectus proin nibh. Mauris ultrices eros in cursus turpis massa tincidunt dui. Aliquet porttitor lacus luctus accumsan tortor posuere ac. Tempus urna et pharetra pharetra massa massa ultricies.
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Dolor sit amet consectetur adipiscing elit. Eget velit aliquet sagittis id consectetur purus ut. Congue nisi vitae suscipit tellus. Quis viverra nibh cras pulvinar mattis nunc sed blandit libero. Arcu cursus vitae congue mauris rhoncus aenean vel. In est ante in nibh mauris cursus mattis molestie a. Tristique risus nec feugiat in fermentum posuere. Urna condimentum mattis pellentesque id nibh tortor id aliquet lectus. Velit egestas dui id ornare arcu odio ut sem nulla. At in tellus integer feugiat scelerisque varius morbi. Adipiscing elit pellentesque habitant morbi tristique senectus et netus et. Faucibus a pellentesque sit amet porttitor eget dolor. Sollicitudin nibh sit amet commodo nulla facilisi nullam. Id eu nisl nunc mi ipsum faucibus vitae. Amet consectetur adipiscing elit duis tristique sollicitudin. Id nibh tortor id aliquet lectus proin nibh. Mauris ultrices eros in cursus turpis massa tincidunt dui. Aliquet porttitor lacus luctus accumsan tortor posuere ac. Tempus urna et pharetra pharetra massa massa ultricies.
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Dolor sit amet consectetur adipiscing elit. Eget velit aliquet sagittis id consectetur purus ut. Congue nisi vitae suscipit tellus. Quis viverra nibh cras pulvinar mattis nunc sed blandit libero. Arcu cursus vitae congue mauris rhoncus aenean vel. In est ante in nibh mauris cursus mattis molestie a. Tristique risus nec feugiat in fermentum posuere. Urna condimentum mattis pellentesque id nibh tortor id aliquet lectus. Velit egestas dui id ornare arcu odio ut sem nulla. At in tellus integer feugiat scelerisque varius morbi. Adipiscing elit pellentesque habitant morbi tristique senectus et netus et. Faucibus a pellentesque sit amet porttitor eget dolor. Sollicitudin nibh sit amet commodo nulla facilisi nullam. Id eu nisl nunc mi ipsum faucibus vitae. Amet consectetur adipiscing elit duis tristique sollicitudin. Id nibh tortor id aliquet lectus proin nibh. Mauris ultrices eros in cursus turpis massa tincidunt dui. Aliquet porttitor lacus luctus accumsan tortor posuere ac. Tempus urna et pharetra pharetra massa massa ultricies.</p>
            </div>
        </section>
    )
}

export default About